import COLORS from "@/constants/colors";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    padding: 16,
    paddingBottom: 0,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
  },
  profileHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.cardBackground,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
    // marginBottom: 16,
  },
  initials: {
    fontSize: 32,
    fontFamily: "Poppins-Medium",
    includeFontPadding: false,
    color: "white",
    textShadowColor: "rgba(0, 0, 0, 0.1)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  profileInfo: {
    flex: 1,
    paddingLeft: 20,
  },
  username: {
    fontSize: 20,
    color: COLORS.textPrimary,
    fontFamily: "Poppins-Bold",
    includeFontPadding: false,
    marginBottom: 4,
  },
  email: {
    fontSize: 14,
    color: COLORS.textSecondary,
    fontFamily: "Poppins-Regular",
    includeFontPadding: false,
    marginBottom: 4,
  },
  logoutButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  logoutText: {
    color: COLORS.white,
    fontFamily: "Poppins-Medium",
    includeFontPadding: false,
    marginLeft: 8,
  },
  challengesHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  challengesTitle: {
    fontSize: 18,
    color: COLORS.textPrimary,
    fontFamily: "Poppins-Medium",
    includeFontPadding: false,
  },
  challengesCount: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  challengesList: {
    paddingBottom: 20,
  },
  challengeItem: {
    flexDirection: "row",
    backgroundColor: COLORS.cardBackground,
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  challengeImage: {
    width: 70,
    height: 100,
    borderRadius: 8,
    marginRight: 12,
  },
  challengeInfo: {
    flex: 1,
    justifyContent: "space-between",
  },
  challengeTitle: {
    fontSize: 16,
    color: COLORS.textPrimary,
    fontFamily: "Poppins-Medium",
    includeFontPadding: false,
    marginBottom: 4,
  },
  challengeDescription: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    includeFontPadding: false,
    color: COLORS.textDark,
    marginBottom: 4,
    flex: 1,
  },
  challengeDate: {
    fontSize: 12,
    color: COLORS.textSecondary,
  },
  deleteButton: {
    padding: 8,
    justifyContent: "center",
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
    marginTop: 20,
  },
  emptyText: {
    fontSize: 16,
    fontFamily: "Poppins-Medium",
    includeFontPadding: false,
    color: COLORS.textPrimary,
    marginTop: 16,
    marginBottom: 20,
    textAlign: "center",
  },
  addButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  addButtonText: {
    color: COLORS.white,
    fontFamily: "Poppins-Medium",
    includeFontPadding: false,
    fontSize: 14,
  },
});

export default styles;
